name: lazy_clock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.4.0
  google_fonts: ^6.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/app-clock.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/app-clock.png"
